# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- deploy

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  PORT: '3000'
  MONGODB_URI: 'mongodb://localhost/testdb'
  SECRET: 'GUUUUUUUUURRRRRRRLLLLL'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run dbOn
    npm run build
    npm test
  displayName: 'npm install and build and test'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TEST-RESULTS.xml'
